### ISSUE TITLE
Start service when device is plugged in

### ISSUE THREAD

**Issue by pepijndevos** [jerr0328/co2mini#1]
Hi thanks for pointing out that these devices have data logging.

I've taken some of your stuff and added them to https://github.com/pepijndevos/rs-co2mon and thought you might be interested to steal my udev/systemd setup, which is hot-pluggable. It seems your udev rule just sets the permissions and the service just runs at startup, while with my rules, udev launches the service when the device is plugged in.

Also the Rust code I forked seems to just open a specific VID:PID rather than taking a device path, which seems more reliable to me. I'd expect Python to also have this option.

**Comment by jerr0328** [comment]
Thanks, I'm finally getting around to updating this. I think opening USB devices directly in Python might need other dependencies, whereas opening it as a file seems to work best for the *nix world.
